# Generated by Django 5.0.1 on 2024-02-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('age', models.SmallIntegerField(verbose_name='年龄')),
                ('sex', models.SmallIntegerField(choices=[(0, '男'), (1, '女'), (2, '保密')], verbose_name='性别有男，女，保密')),
                ('birthday', models.DateField(verbose_name='生日')),
            ],
            options={
                'db_table': 'db_student',
            },
        ),
    ]
